### ISSUE TITLE
SIGWX Object - Jet stream: Why is there a need to describe a jet stream separately by a set of core points and a set of wind symbols

### ISSUE THREAD

**Issue by blchoy** [blchoy/iwxxm-testbedOne#1]
In the current representation, the jet stream is described separately by a set of core points and a set of wind symbols, but they are mixed together in the BUFR file.  The core points have latitudes and longitudes only while the wind symbols has latitudes, longitudes and heights.  During rendering, the core points are being used for the plotting of a line (cubic spline) indicating the jet core annotated by wind symbols with other attributes.

Question is, whether it would be simpler in future to have a single set of 2.5D points to represent the jet stream which is much simpler that what we have right now?  The reason for using 2.5D points is that it is difficult to create a smooth line joining the points to represent the jet core in 3D space.  When the user application draws the jet core, chances are it is being viewed as a single layer projected on the earth's surface and we can use the lat/long part of the points to create the cubic spline as what we are doing right now.  If we are viewing the jet core from an oblique direction (e.g. side way), then the only efficient way to do so is to connect them with straight lines which should be good enough for viewing purpose.

By the way, we only provide the upper and lower boundaries of the 80kt isotach.  Will there be any benefits to also provide the horizontal boundaries at the same time?

Happy to discuss.

**Comment by GAndrsn** [comment]
I've copied and pasted the text of my email below to keep things in one place:

As far as I can see, there are two options for how jets are laid out in IWXXM files:

Option A: Jet core and jet symbol points together.

                Jet 1
                                Point 1: x, y, z=NaN, s=NaN
                                Point 2: x, y, z=NaN, s=NaN
                                Point 3: x, y, z=FL300, s=100kts
                                Point 4: x, y, z=NaN, s=NaN
                Jet 2
                                Point 1: x, y, z=NaN, s=NaN
                                Point 2: x, y, z=FL350, s=90kts
                                Point 3: x, y, z=NaN, s=NaN
                                Point 4: x, y, z=NaN, s=NaN

Option B: Jet core points followed by jet symbol points, linked to a jet.

                Jet 1
                                Point 1: x, y
                                Point 2: x, y
                                Point 3: x, y
                Jet 2
                                Point 1: x, y
                                Point 2: x, y
                                Point 3: x, y
                Symbol points
                                Point 1: x, y, z=FL300, s=100kts, jet=1
                                Point 2: x, y, z=FL350, s=90kts, jet=2

I left top/base info out intentionally, for simplicity.

I think the current BUFR format is more like Option A. I would need to read up more on what any current documentation for IWXXM implies should be the preferred option in the future. I think keeping all the points associated with a jet together as in Option A makes more sense in terms of clarity, but if there’s a coding reason for keeping things separate then I can be persuaded to go with Option B.

**Comment by GAndrsn** [comment]
> Will there be any benefits to also provide the horizontal boundaries at the same time?

I've just discussed this with Karen (she doesn't currently ahve a GitHub account). She says it's been discussed with the Americans, and although all sides can see the potential benefit of including horizontal extent, it's not planned to be included at this time. This is because the SigWx charts provide a simple overview, and adding more info complicates the chart. The advice for users would be that if thaey want that sort of info they can always dig into the gridded wind data files.

My feeling on the height of wind fletch points is that the height value is simply used as a text label, keeping the jet objects as 2.5D, as opposed to trying to use fletch heights to draw 3D-splined jets. I don't know the technical feasibility of this approach though.

**Comment by blchoy** [comment]
This is Jet 1 in Option A in XML:
```
<SIGWXFeature gml:id="...">
  <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionA"/>
  <FeatureCollection>
    <SIGWXFeature gml:id"...">
      <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionA/corePoints"/>
      <Geometry>
        <gml:Point gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
           <gml:pos>...Point 1...</gml:pos>
        </gml:Point>
      </Geometry>
    </SIGWXFeature>
    <SIGWXFeature gml:id"...">
      <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionA/corePoints"/>
      <Geometry>
        <gml:Point gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
           <gml:pos>...Point 2...</gml:pos>
        </gml:Point>
      </Geometry>
    </SIGWXFeature>
    <SIGWXFeature gml:id"...">
      <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionA/windFletchPoints"/>
      <Geometry>
        <gml:Point gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
           <gml:pos>...Point 3...</gml:pos>
        </gml:Point>
      </Geometry>
      <Attribute xlink:href="http://codes.wmo.int/.../elevation">FL300</Attribute>
      <Attribute xlink:href="http://codes.wmo.int/.../JetStreamOptionA/coreSpeed">100</Attribute>
    </SIGWXFeature>
    <SIGWXFeature gml:id"...">
      <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionA/corePoints"/>
      <Geometry>
        <gml:Point gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
           <gml:pos>...Point 4...</gml:pos>
        </gml:Point>
      </Geometry>
    </SIGWXFeature>
  </FeatureCollection>
</SIGWXFeature>
```
For this representation, WAFCs has to inform the end users to render the jet core using only the core points and rendered using cubic spline separately (e.g. user guide).

This is Jet 1 in Option B in XML:
```
<SIGWXFeature gml:id="...">
  <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionB/corePoints"/>
  <Geometry>
    <gml:Curve gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
      <gml:segments>
        <gml:CubicSpline>
          <gml:posList>...Point 1, Point 2, Point 4...</gml:posList>
          <gml:vectorAtStart>...</gml:vectorAtStart>
          <gml:vectorAtEnd>...</gml:vectorAtEnd>
        </gml:CubicSpline>
      </gml:segments>
    </gml:Curve>
  </Geometry>
</SIGWXFeature>
<SIGWXFeature gml:id="...">
  <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionB"/>
  <FeatureCollection>
    <SIGWXFeature gml:id"...">
      <FeatureType xlink:href="http://codes.wmo.int/.../JetStreamOptionB/windFletchPoints"/>
      <Geometry>
        <gml:Point gml:id="..." srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
           <gml:pos>...Point 3...</gml:pos>
        </gml:Point>
      </Geometry>
      <Attribute xlink:href="http://codes.wmo.int/.../elevation">FL300</Attribute>
      <Attribute xlink:href="http://codes.wmo.int/.../JetStreamOptionB/coreSpeed">100</Attribute>
    </SIGWXFeature>
    <Attribute xlink:href="http://codes.wmo.int/.../corePointsReference">...gml:id of the core points feature...</Attribute>
  </FeatureCollection>
</SIGWXFeature>
```
This option has the benefit that the required information for rendering (list of core points, cubic spline) are already included in the XML document (it also means that one can change on the fly).  There is also unambiguous separation of core and wind fletch points (the core points are used for plotting the jet core, the wind fletch points are for separate display).  The drawback is that it needs a reference, or otherwise, to indicate that the core points and wind fletch points are coming from the same object.

**Comment by blchoy** [comment]
> The advice for users would be that if they want that sort of info they can always dig into the gridded wind data files.

There are similar debates on ease of use regarding geographical contours and Digital Elevation Model (DEM).  No doubt that the conclusion will involve the need to make reference to use cases, but I think end user device capability (Can it handle high resolution gridded data? Vector data seems to have an edge on mobile device, if this is one of the target device for rendering SIGWX chart) is also important.

**Comment by blchoy** [comment]
To facilitate further discussion, may I suggest an Option C which has:
```
          Jet 1
                              Point 1: x, y, z=FL300, s=100kt, d=270deg
                              Point 2: x, y, z=FL310, s=120kt, d=260deg
                              Point 3: x, y, x=FL320, s=140kt, d=250deg
                              ...
```
To render the jet core as a projection onto the earth's surface (i.e. 2D), just take the lat/long from these points and use cublic spline to interpolate.  The tangential wind direction is also proposed to be included to simplify calculation.

**Comment by blchoy** [comment]
I got this from an elementary mathematics text book which may better describe the situation:

![image](https://user-images.githubusercontent.com/30064374/63398316-c757af00-c3ff-11e9-9147-4f572edeb16a.png)

If this is Jet 1, Points 1, 2 and 4 has no elevation and they are the only points used for rendering of the projected jet core.  Point 3 will be plotted on top of the projected jet core with the wind symbol, elevation and other information as annotation.  The data in BUFR file is more for rendering of the jet on a chart than representing the jet itself.

In IWXXM we want to move from product (here data for rendering) to data centric.  So we may want to describe the actual jet a bit more?

**Comment by GAndrsn** [comment]
Sorry for not getting back into the discussion on this sooner, I've been involved in other work. I think there's a question here over whether wind fletch points are separate from core points, or are actually core points with additional data. My interpretation of the current BUFR data is that the latter is true, so I assumed that this is how things will be with IWXXM. I think your suggestions here are on the basis that fletch points are not core points. I'll check with Karen her thoughts.

Edit: Sorry, re-reading your comments above makes me think you're aware of the above distinction. My feeling is that Option A makes more sense if fletch points are also core points, and Option B makes more sense if fletch points are not core points. To be honest, my code can generate fletch points to be either, so either option is plausible as a way forward.

**Comment by marqh** [comment]
> 
> Option B: Jet core points followed by jet symbol points, linked to a jet.
> 
> ```
>             Jet 1
>                             Point 1: x, y
>                             Point 2: x, y
>                             Point 3: x, y
>             Jet 2
>                             Point 1: x, y
>                             Point 2: x, y
>                             Point 3: x, y
>             Symbol points
>                             Point 1: x, y, z=FL300, s=100kts, jet=1
>                             Point 2: x, y, z=FL350, s=90kts, jet=2
> ```

Option C: all points have lat lon pair, a separate altitude, and an optional speed
 ```
             Jet 1
                             Point 1: x, y, z=FL300, s=missing
                             Point 2: x, y, z=FL250, s=100kts
                             Point 3: x, y, z=FL300, s=missing
             Jet 2
                             Point 1: x, y, z=FL300, s=missing
                             Point 2: x, y, z=FL350, s=missing
                             Point 3: x, y, z=FL350, s=90kts
 ```

Option C would still keep the 2D horizontal points with respect to a WGS84 CRS and a separate set of altitudes, as flight levels
There is a challenge in this option, matching lists of lat-lon pairs to lists of n/2 length

This challenge would need to be addressed, and (I think) validated for

**Comment by marqh** [comment]
matching arrays would enable separate XML elements to be used for horizontal position (2n), inlcuding spline interpolation, and for altitude (n), altitude bounds (2n), wind speed and other aspects

validation of side by side XML elements with lists of values, where the nubmer of items has to match, based on element type

**Comment by marqh** [comment]
Option D; All points have all data elements, business rule flags are also provided, enabling explicit specification in the information of where plot options may be taken.

```
            Jet 1
                            Point 1: x, y, z=FL300, s=70kts, plotFletch=False
                            Point 2: x, y, z=FL250, s=100kts, plotFletch=True
                            Point 3: x, y, z=FL300, s=60kts, plotFletch=False
            Jet 2
                            Point 1: x, y, z=FL300, s=50kts,  plotFletch=False
                            Point 2: x, y, z=FL350, s=60kts, plotFletch=False
                            Point 3: x, y, z=FL350, s=90kts, plotFletch=True

```

**Comment by blchoy** [comment]
FIXM is making reference (indirectly) to [AIXM Route](http://aixm.aero/sites/aixm.aero/files/imce/AIXM511HTML/AIXM/Diagram_RouteSegment.html) to describe flight paths. Looking at [the examples](https://ext.eurocontrol.int/aixm_confluence/pages/viewpage.action?pageId=3087279) it was noticed that a route segment is basically a vertical cross-section bounded by vertical lines at the start and end points and geodesic lines connecting the start and end points at the lower and upper limits of the segment.  If we do the same thing for our jet stream it will look (from side way) something like:

![jetstream](https://user-images.githubusercontent.com/30064374/73428275-acf10c80-4373-11ea-8ac0-a06121da4374.png)

where the dash line is the jet stream and the rectangles representation of the jet stream segments represented in AIXM way.

**Comment by blchoy** [comment]
After all the discussions it seems to me that the pragmatic way to move forward is to present the jet stream object with the 2D jet core as the geometry and the wind symbols in the property section.  The follow example comes from the Guide and coded in the newly developed schema:

```
    <!-- A Jet Stream Object -->
    <iwxxm:feature>
        <iwxxm:MeteorologicalFeature gml:id="uuid.8c3d3467-e398-4627-ab23-f9e57c2215b5">
            <gml:identifier codeSpace="http://wafc/sigwxobj">eb324455-236c-46f8-b80d-c6d42c3a634c</gml:identifier>
            <iwxxm:phenomenonTime>
                <gml:TimeInstant gml:id="uuid.26328dbd-c763-4fd4-9b3c-40a6400795f0">
                    <gml:timePosition>2001-01-31T00:00:00Z</gml:timePosition>
                </gml:TimeInstant>
            </iwxxm:phenomenonTime>
            <iwxxm:phenomenon xlink:href="http://codes.wmo.int/bufr4/codeflag/0-28-011/JETSTREAM"/>
            <iwxxm:phenomenonGeometry>
                <gml:Curve gml:id="uuid.7b5a197a-d9bf-4f3b-ba36-701fe019b6d2" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                    <gml:segments>
                        <gml:CubicSpline>
                            <gml:posList>35.4 -104.7 36.1 -101.6 36.6 -99.6 36.9 -97.7 37.4 -94.9 38.3 -92.3 39.2 -90.3 40.7 -88.1 41.5 -86.3 42.0 -82.7 41.9 -78.9</gml:posList>
                            <gml:vectorAtStart>1.0 2.0</gml:vectorAtStart>
                            <gml:vectorAtEnd>2.0 3.0</gml:vectorAtEnd>
                        </gml:CubicSpline>
                    </gml:segments>
                </gml:Curve>
            </iwxxm:phenomenonGeometry>
            <iwxxm:phenomenonProperty>
                <iwxxm:WAFCJetStreamWindSymbol gml:id="uuid.69a048d7-ba8d-47d5-9e5d-15c658f99e87">
                    <iwxxm:location>
                        <iwxxm:ElevatedPoint gml:id="uuid.2efe3eff-3ef0-4817-b2ab-b670417ebb6a" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                            <gml:pos>36.1 -101.6</gml:pos>
                            <iwxxm:elevation uom="M">10668</iwxxm:elevation>
                            <iwxxm:verticalReference>MSL</iwxxm:verticalReference>
                        </iwxxm:ElevatedPoint>
                    </iwxxm:location>
                    <iwxxm:windSpeed uom="m/s">51.5</iwxxm:windSpeed>
                </iwxxm:WAFCJetStreamWindSymbol>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:WAFCJetStreamWindSymbol gml:id="uuid.1bf0cb18-199d-4467-865d-3e8c4923de96">
                    <iwxxm:location>
                        <iwxxm:ElevatedPoint gml:id="uuid.b40fe04a-174f-4dac-94b4-987c4d729de4" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                            <gml:pos>36.9 -97.7</gml:pos>
                            <iwxxm:elevation uom="M">15240</iwxxm:elevation>
                            <iwxxm:verticalReference>MSL</iwxxm:verticalReference>
                        </iwxxm:ElevatedPoint>
                    </iwxxm:location>
                    <iwxxm:windSpeed uom="m/s">61.8</iwxxm:windSpeed>
                    <iwxxm:IsotachUpperElevation uom="M">15240</iwxxm:IsotachUpperElevation>
                    <iwxxm:IsotachUpperVerticalReference>MSL</iwxxm:IsotachUpperVerticalReference>
                    <iwxxm:IsotachLowerElevation uom="M">13716</iwxxm:IsotachLowerElevation>
                    <iwxxm:IsotachLowerVerticalReference>MSL</iwxxm:IsotachLowerVerticalReference>
                </iwxxm:WAFCJetStreamWindSymbol>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:WAFCJetStreamWindSymbol gml:id="uuid.f9847b29-2d86-4bda-b69b-d3fae1e29e43">
                    <iwxxm:location>
                        <iwxxm:ElevatedPoint gml:id="uuid.1b2dd415-451d-4f04-bd67-794ed859f845" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                            <gml:pos>38.3 -92.3</gml:pos>
                            <iwxxm:elevation uom="M">15240</iwxxm:elevation>
                            <iwxxm:verticalReference>MSL</iwxxm:verticalReference>
                        </iwxxm:ElevatedPoint>
                    </iwxxm:location>
                    <iwxxm:windSpeed uom="m/s">51.5</iwxxm:windSpeed>
                </iwxxm:WAFCJetStreamWindSymbol>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:WAFCJetStreamWindSymbol gml:id="uuid.06af45b6-4852-41e0-b211-5aa6daa03f83">
                    <iwxxm:location>
                        <iwxxm:ElevatedPoint gml:id="uuid.f26f3ec6-ec91-4770-b04e-f9097a02cb19" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                            <gml:pos>40.7 -88.1</gml:pos>
                            <iwxxm:elevation uom="M">15240</iwxxm:elevation>
                            <iwxxm:verticalReference>MSL</iwxxm:verticalReference>
                        </iwxxm:ElevatedPoint>
                    </iwxxm:location>
                    <iwxxm:windSpeed uom="m/s">61.8</iwxxm:windSpeed>
                    <iwxxm:IsotachUpperElevation uom="M">16154</iwxxm:IsotachUpperElevation>
                    <iwxxm:IsotachUpperVerticalReference>MSL</iwxxm:IsotachUpperVerticalReference>
                    <iwxxm:IsotachLowerElevation uom="M">14326</iwxxm:IsotachLowerElevation>
                    <iwxxm:IsotachLowerVerticalReference>MSL</iwxxm:IsotachLowerVerticalReference>
                </iwxxm:WAFCJetStreamWindSymbol>
            </iwxxm:phenomenonProperty>
            <iwxxm:phenomenonProperty>
                <iwxxm:WAFCJetStreamWindSymbol gml:id="uuid.c6ccf151-6a61-479d-b316-bdab7a27bfcc">
                    <iwxxm:location>
                        <iwxxm:ElevatedPoint gml:id="uuid.2e67726d-b5f4-4805-bae8-a45f18c34d22" srsDimension="2" axisLabels="Lat Long" srsName="http://www.opengis.net/def/ers/EPSG/0/4326">
                            <gml:pos>42.0 -82.7</gml:pos>
                            <iwxxm:elevation uom="M">9144</iwxxm:elevation>
                            <iwxxm:verticalReference>MSL</iwxxm:verticalReference>
                        </iwxxm:ElevatedPoint>
                    </iwxxm:location>
                    <iwxxm:windSpeed uom="m/s">51.5</iwxxm:windSpeed>
                </iwxxm:WAFCJetStreamWindSymbol>
            </iwxxm:phenomenonProperty>
        </iwxxm:MeteorologicalFeature>
    </iwxxm:feature>
```

I have to say that this is a very inefficient way of storing data but should be more flexible in implementing on different storage and information exchange systems.

**Comment by blchoy** [comment]
I see no further need for discussion on this topic right now so I am closing it.
